---
title: "House prices"
author: "Kirill Setdekov"
date: '17 февраля 2019 г '
output: html_document
keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup libraries
```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(party)

```

## load data
```{r message=FALSE}
train <- read_csv("data/train.csv")
test <- read_csv("data/test.csv")
```

```{r}
qplot(train$SalePrice)
```

Select only numeric for a simple test run pairs
```{r}
trainnum<- dplyr::select_if(train, is.numeric)
pairs(trainnum[,c(1:10, 38)])
 qplot(train$YearBuilt, train$YearRemodAdd)
 ggplot(data=trainnum, mapping = aes(x=YearBuilt, y=YearRemodAdd, colour=log(SalePrice)))+geom_point()
qplot(trainnum$YrSold)
```

## simple linear regression
```{r}
dumbreg <- lm(SalePrice~.,trainnum)
summary(dumbreg)

testNafixed1 <- test
```


```{r warning=FALSE}
testNafixed1[] <- lapply(testNafixed1, function(x) { 
  x[is.na(x)] <- mean(x, na.rm = TRUE)
  x
})
```

```{r}

submission1<- testNafixed1[,1]

submission1$SalePrice <- predict.lm(dumbreg, testNafixed1)
write.csv(submission1,"submission1.csv",row.names=FALSE)
```
1 отправка просто линейной ригрессии

Нужно обработать пустые переменные

## submission 2
# factor prosessing
```{r}
with(train, table(MSSubClass))
with(train, table(MSZoning))
with(train, table(Street))
with(train, table(Alley))
train$Alley[is.na(train$Alley)] <- "no"
with(train, table(LotShape))


train <-
train %>% mutate(
MSSubClass = factor(MSSubClass),
MSZoning = factor(MSZoning),
Street = factor(Street),
Alley = factor(Alley),
LotShape=factor(LotShape, levels= c("Reg", "IR1", "IR2", "IR3"),ordered = TRUE)
) 
```

```{r}
cfit <- ctree(SalePrice ~ MSSubClass+MSZoning+Street+Alley+Alley+LotShape,train)
plot(cfit)
```


